### ISSUE TITLE
No se ve el titulo y descripción

### ISSUE THREAD

**Issue by gvarela1981** [ign-argentina/anida-web#1]
Despues del commit da6133be544184d85ff3682e0b03763e44e46cf3 donde se movió los datos de la página a un json, se produce un error javascript y no se visualiza el nombre y descripcion de la página
![error1](https://user-images.githubusercontent.com/9384999/46671986-ab169f00-cbac-11e8-9d07-d0255bb35171.PNG)
![error2](https://user-images.githubusercontent.com/9384999/46671992-af42bc80-cbac-11e8-99fb-9c51640c4c9d.PNG)

Si se ejeucuta el código después de que la página cargó, el problema se arregla porque la variable page ya existe en memoria

**Comment by Zalitoar** [comment]
Solucionado en #da6133b
